INSERT INTO Dept
VALUES(10,'ACCOUNTING','NEW YORK');
INSERT INTO Dept
VALUES(20,'RESEARCH','DALLAS');
INSERT INTO Dept
VALUES(30,'SALES','CHICAGO');
INSERT INTO Dept
VALUES(40,'OPERATIONS','BOSTON');